spec:
    crossplane:
        enabled: true # install crosplane controller
    provider:
        aws:
            version: v0.16.0 # install aws provider version
            serviceAccount:
                annotations: {} # provider service annotaion
    aws:
        enabled: true
    destination:
        clustername: test
        server: https://kubernetes.default.svc # agocd registered server address
        name: test
        project: kube-addons-crossplane-config # agocd project name
