{{ if .Values.spec.provider.aws.enabled -}}
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: provider-aws-controller-config
  annotations:
  {{- if .Values.spec.provider.aws.serviceAccount.annotations -}}
     {{- toYaml .Values.spec.provider.aws.serviceAccount.annotations | nindent 4 }}
  {{- end }}
spec:
  podSecurityContext:
    fsGroup: 2000
{{- end }}